/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2010 BiBiServ Curator Team, http://bibiserv.cebitec.uni-bielefeld.de,
 * All rights reserved.
 *
 * The contents of this file are subject to the terms of the Common
 * Development and Distribution License("CDDL") (the "License"). You
 * may not use this file except in compliance with the License. You can
 * obtain a copy of the License at http://www.sun.com/cddl/cddl.html
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.  When distributing the software, include
 * this License Header Notice in each file.  If applicable, add the following
 * below the License Header, with the fields enclosed by brackets [] replaced
 *  by your own identifying information:
 *
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * Contributor(s):
 *
 */
package <#getPackageName/#>;

import de.unibi.cebitec.bibiserv.util.validate.*;
import de.unibi.techfak.bibiserv.util.ontoaccess.bibiontotypes.OntoRepresentation;
import de.unibi.techfak.bibiserv.exception.BiBiToolsException;
import de.unibi.cebitec.bibiserv.utils.UniversalValidator;
import de.unibi.cebitec.bibiserv.utils.UniversalConverter;
import de.unibi.cebitec.bibiserv.util.convert.ConversionException;

import de.unibi.techfak.bibiserv.web.beans.session.MessagesInterface;
import java.io.InputStream;

/**
 * Utilities class - offers validation methods for all input output types used within
 * generated tool.
 * <b>Attention: This is autogenerated code. </b>
 *
 *
 * @author Jan Krueger - jkrueger[aet]cebitec.uni-bielefeld.de (template)
 * @author Thomas Gatter - tgatter[aet]cebitec.uni-bielefeld.de
 */
public class Utilities {
 

   /* generated validator method for all input/output types. Valid if no error */   
     public static Object validate(Object content, OntoRepresentation representation) throws ValidationException, BiBiToolsException{
        return UniversalValidator.validate(content, representation);
     }
     
    /* generate converter method */
     public static Object convert(Object object, OntoRepresentation from, OntoRepresentation to)
             throws BiBiToolsException, ConversionException {
         return convert(object, from, to, false);
     }
     
     public static Object convert(Object object, OntoRepresentation from, OntoRepresentation to, boolean streaming)
            throws BiBiToolsException, ConversionException {
         
         if (streaming) {
             // if data is long conversion is done on the fly via stream-converter
             if(!(object instanceof InputStream)) {
                 throw new ConversionException("Streamconversion called with non-stream as object.");
             }
             return UniversalConverter.streamConvert((InputStream) object, from, to);
         } else {
             return UniversalConverter.convert(object, from, to);
         }
     }

   /* generated validator methods for all (enum) parameters */
     <#generateParamValidators/#>

     <#generateEnumParamValidators/#>

}
